# Generated by Django 6.0.3 on 2026-04-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Gambar'),
        ),
    ]
