# Generated by Django 6.0.3 on 2026-05-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_produk_gambar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='gambar_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Gambar'),
        ),
    ]
