# Generated by Django 6.0.3 on 2026-05-22 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_alter_produk_gambar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ulasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengulas', models.CharField(max_length=100, verbose_name='Nama')),
                ('email_pengulas', models.EmailField(max_length=254, verbose_name='Email')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('komentar', models.TextField(verbose_name='Komentar')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ulasan/', verbose_name='Foto (opsional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disetujui', models.BooleanField(default=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.produk')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
